name: Publish to crates.io
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --all
      - name: Check if version changed
        id: check_version
        run: |
          CURRENT_VERSION=$(cargo pkgid | cut -d# -f2)
          PUBLISHED_VERSION=$(cargo search ${{ github.event.repository.name }} --limit 1 | sed -nE 's/^[^"]*"//; s/".*//p')
          if [ "$CURRENT_VERSION" != "$PUBLISHED_VERSION" ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
      - uses: katyo/publish-crates@v2
        if: steps.check_version.outputs.changed == 'true'
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
